name: ecco_energi
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  firebase_core: ^2.15.0
  firebase_storage: ^11.2.5
  firebase_auth: ^4.7.0
  google_sign_in: ^6.1.4
  charts_flutter: ^0.12.0
  cloud_firestore: ^4.8.3
  flutter_launcher_icons: ^0.13.1
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.2
  provider: ^6.0.5
  shared_preferences: ^2.2.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/data.json
    - assets/images/

flutter_icons:
  image_path: "assets/icon/icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  ios: true
  android: true