// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCAYzwP1wc10hH-PXzRAk8RWwOxmW3Kp-4',
    appId: '1:1061561441224:web:07833d896fa498b9efbefd',
    messagingSenderId: '1061561441224',
    projectId: 'myappufrpe-ae955',
    authDomain: 'myappufrpe-ae955.firebaseapp.com',
    databaseURL: 'https://myappufrpe-ae955-default-rtdb.firebaseio.com',
    storageBucket: 'myappufrpe-ae955.appspot.com',
    measurementId: 'G-17BLQ2PQTP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD411Gk51btPaTpXc5pu_00FKoOokZ3lB4',
    appId: '1:1061561441224:android:d5420c28b51855e1efbefd',
    messagingSenderId: '1061561441224',
    projectId: 'myappufrpe-ae955',
    databaseURL: 'https://myappufrpe-ae955-default-rtdb.firebaseio.com',
    storageBucket: 'myappufrpe-ae955.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCxKMwncUSJ_SUyQeeLBkkJucuAnG9xbjo',
    appId: '1:1061561441224:ios:651da3355bdad300efbefd',
    messagingSenderId: '1061561441224',
    projectId: 'myappufrpe-ae955',
    databaseURL: 'https://myappufrpe-ae955-default-rtdb.firebaseio.com',
    storageBucket: 'myappufrpe-ae955.appspot.com',
    androidClientId: '1061561441224-qe4hg2f4rj7uufk6b76lsq24g2gveos0.apps.googleusercontent.com',
    iosClientId: '1061561441224-pibgsrdhmhbke5tdfgq7ftn006omkr7m.apps.googleusercontent.com',
    iosBundleId: 'com.example.eccoEnergi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCxKMwncUSJ_SUyQeeLBkkJucuAnG9xbjo',
    appId: '1:1061561441224:ios:651da3355bdad300efbefd',
    messagingSenderId: '1061561441224',
    projectId: 'myappufrpe-ae955',
    databaseURL: 'https://myappufrpe-ae955-default-rtdb.firebaseio.com',
    storageBucket: 'myappufrpe-ae955.appspot.com',
    androidClientId: '1061561441224-qe4hg2f4rj7uufk6b76lsq24g2gveos0.apps.googleusercontent.com',
    iosClientId: '1061561441224-pibgsrdhmhbke5tdfgq7ftn006omkr7m.apps.googleusercontent.com',
    iosBundleId: 'com.example.eccoEnergi',
  );
}
